### ISSUE TITLE
Algorithm factory issue

### ISSUE THREAD

**Issue by TomDoesb** [UOC/java-lti-1.3-jwt#4]
Why did you choose to build the private key in this manner (AlgorithmFactory.java)

```
DerInputStream derReader = new DerInputStream(Base64.getDecoder().decode(privateKey));

			DerValue[] seq = derReader.getSequence(0);

			if (seq.length < 9) {
				throw new GeneralSecurityException("Could not parse a PKCS1 private key.");
			}

			// skip version seq[0];
			BigInteger modulus = seq[1].getBigInteger();
			BigInteger publicExp = seq[2].getBigInteger();
			BigInteger privateExp = seq[3].getBigInteger();
			BigInteger prime1 = seq[4].getBigInteger();
			BigInteger prime2 = seq[5].getBigInteger();
			BigInteger exp1 = seq[6].getBigInteger();
			BigInteger exp2 = seq[7].getBigInteger();
			BigInteger crtCoef = seq[8].getBigInteger();

			RSAPrivateCrtKeySpec keySpecPv = new RSAPrivateCrtKeySpec(modulus, publicExp, privateExp, prime1, prime2, exp1, exp2, crtCoef);

			this.privateKey = (RSAPrivateKey) kf.generatePrivate(keySpecPv);
```

Rather than

```
KeyFactory keyFactory = KeyFactory.getInstance("RSA");
PKCS8EncodedKeySpec privateKeySpec = new PKCS8EncodedKeySpec(Base64.decode(base64EncodedRsaPrivateKey));
privateKey = keyFactory.generatePrivate(privateKeySpec);
```

When using a correct PKCS8 private key your algorithm factory fails with a
 `GeneralSecurityException`

**Comment by TomDoesb** [comment]
example private key: 

`MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDSobsInMvkeFKW4UUWCqka+eQtlauTc+naiYPgPEAC2o/7VrINCxac/WUjet3VtoieBrSa4sU/GmVuxR/rDLtC+Qh/N7kFWRXIp2YUTi/iLGyQmwszhhnwJtz8paBwKhmQarXjKH+8JqUKA9D8K2A88vSAymyBxmshYTCEScHdOLrnwZyA9Ji8TGrYa42JrYPlhpLH7wFD+cwZWUDRnA0kCqqZrlxkpG8VzhGJYTaXbrML2Prv0b9RQKY61y7KVy9RBVbQy0JrLohLgPGS1xym6LLmjDb5CJ9vgk2bjNILeX0MUYFtaaw+sVygU3gHCPyLO94LVPiBBlWL0OypvM05AgMBAAECggEBAIcP/ga/xF50aUEmok5H97e8lXxFhQfARCxGEbIv8DvkOn9IUFPc0FtKgRgHKUhpC6GJWzYWQ7T7EB+/d4AZYdrIJZKuAI5VWYqZDPPoTvwQ0GzJfp1DWE6OHRZEfmRuGoZoZsmKpp3XieyqFdAdYFC02ePb6UguG3QEBkBNq2pWUzAyOZZA+2lZlVmCxDYKhTUvJD3N2/O1olewTM90v/3k5nv62FBzXUctwn0RESgFX63Y2Rxang6bdhuePrK9K6l8WC765seu/vCKjJ5qa/GSSbwluNMXPXLKQ65OA0+QrxFs5+blvHZxvMRPNIpopfGNkjpwg/s/mbUf0d4zpaECgYEA/q8WDERtKf/AdLTCN/MnlqZsG4Qg9diosewp3LUSGd+9HMA1JhlU22cHHc/sJlfJTwWlgBqZExH0JOPhTk/0TuzBJo3YLWbjaR0MBjnEUdmBwauVtltd8Bfe10BUSnzt0iGJH2Y9GAAozpSZHNmhwggmB7zCFOAqEomXTBOyRdMCgYEA07hegQdLuSOjNy4v86Cq5Wbw/Aj4VccfQlmEWxjf0rJEErF0aPUgaokizjsRdj4L+kzpNyiIrfILznFMj4ZZ61D3tvE0J9xxSfkI/Z4JtpolCKHYA2nDux+lFHI2hYZVe9PBjVRVpDQdg+vIb2RkctXQdy2QadGri9Za6zXB/UMCgYEA9kY+brxYR02dP/1u9YV2mbHyRiVdbf4FGo/A50Bc8ZIuH7gpbN7/9G1LL2PY+jbXXkeagya1MQCicm29d+nO1+cO24Y8LaMZcpJ5BygjE/bdB3cxfTYav0mF3eXB3ImzuwdcvnUxzJyS2ThOWtyEE8mnZMH9dwxRAr30BMfjEqsCgYEAo0FspePhUQ6Y4Yjc8ui2PpRFSKMGEuarRPdP5wrkNEy/zwZE9FXoPB4o14uWqG2pwMUjpCO+WRrmXbbhyV5Y4eoaSVfu1rnWJatBcoc1iDeOTPy3W9JnWlhJa92yCv4N1qDvg7I/I5IIHFxovvRTvHUA/ZUF4YMK25Zbnzlhr48CgYBCqAMMuPsFvBkTE500nncnYt1cVbwEgPa7OYrhqJvzz+TEJRBTiE7dynEXeBIzX+pJCEawAbtR1G5TWgO0+mydodorvYkyRbrtSM20wK+CWsVnhJEtdqSlSCpocplwB7EYYNIKLvPEhDCKFVbzZqS7al9x4kL0Un+L/H6/JFD4Zg==`

**Comment by xaviaracil** [comment]
I'm affraid i'm not an expert in java security and the way I found to work with IMS' reference implementation was the code above. 
I'll try your solution, which is better and cleaner, by the way, and merge into the codebase.

Thanks!

**Comment by TomDoesb** [comment]
Thanks! I'm playing around with the reference platform and I am running into issues with the jwt generated by your library and my Keyset end point. 
Have you ever tried to get your own jwkset api endpoint working with the reference platform and your library?
Anyway your lib is saving me a lot of figuring out, thanks for sharing!
